##
## EPITECH PROJECT, 2026
## Zappy/ai/Makefile
##

NAME = zappy_ai

all: ../$(NAME)
.PHONY: all

../$(NAME):
	@echo "Error: $(NAME) is not implemented yet"
	@exit 1

clean fclean tests_run:
	@true
.PHONY: clean fclean tests_run

re: fclean all
.PHONY: re
